---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-config-server
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: spring-config-server
spec:
  ports:
  - name: http
    nodePort: 30705
    port: 18888
    targetPort: 18888
  selector:
    app.kubernetes.io/name: spring-config-server
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-config-server
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: spring-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-config-server
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-config-server
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabricio211/spring-config-server:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: account-service
        ports:
        - containerPort: 18888
          name: http
          protocol: TCP
